### ISSUE TITLE
Explain workflow to publish announcement

### ISSUE THREAD

**Issue by mabotkin** [wuxishy/vmtsite#1]
Could you briefly explain the workflow for making an announcement? Otherwise, site looks excellent.

**Comment by mabotkin** [comment]
Also, how do I make changes and push to live? Do I push to gh-pages with the makefile ( `make gh-pages` )?

**Comment by wuxishy** [comment]
I keep pages under content/pages (they will show up in the menu).

For weekly announcements, I keep the files under content/weekly/$(year), and named as the date of announcement. Then you just tag it as "announcement" in in meta section. I am currently considering change it Announcments.

**Comment by wuxishy** [comment]
Did you see my invite for slack?
You push the generated web files with `make github` It will copy the output to gh-pages branch and then perform a push.
