### ISSUE TITLE
Redirect GitHub Pages link to actual URL

### ISSUE THREAD

**Issue by gengkev** [wuxishy/vmtsite#4]
https://tj-vmt.github.io/vmtsite/
do you see how this is a problem
(create another detached branch containing just a redirect and publish that one instead?)

**Comment by wuxishy** [comment]
tell that to the Canadian, I personally prefer disabling github pages.

**Comment by mabotkin** [comment]
i was thinking of just using the github pages as a development site but i guess since its public people can still find it, if you want just disable it (and update the readme)

**Comment by wuxishy** [comment]
@gengkev Finally, resolved. Thank senioritis for the delay.
